services:
  - type: web
    name: fairweather-sculler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 60 --bind 0.0.0.0:$PORT
    envVars:
      - key: TIDE_API_KEY
        sync: false
      - key: METOFFICE_SITESPECIFIC
        sync: false
